### ISSUE TITLE
MVTec dataset cannot be downloaded

### ISSUE THREAD

**Issue by detectRecog** [raadon96/MVTec-Anomaly-Detection#49]
I think the ftp server might go wrong for the MVTec dataset. The site (ftp://guest:GU.205dldo@ftp.softronics.ch/mvtec_anomaly_detection/mvtec_anomaly_detection.tar.xz) is offline now.

Can you provide a downloadable link for the MVTec dataset. Thank you very much.

**Comment by raadon96** [comment]
Try going to this [page](https://www.mvtec.com/company/research/datasets/mvtec-ad/), scroll down a little and then click on **Download the whole dataset**.

**Comment by detectRecog** [comment]
Hi, thank you for your quick response.
I have tried Chrome and Firefox, none of them work. Does downloading this dataset need to log in or some other operations?
Is there some google drive link for this dataset?

**Comment by raadon96** [comment]
To my knowledge, you don't need to login to be able to download the dataset. Unfortunately, I don't know of another source that contains the dataset.

**Comment by detectRecog** [comment]
Hah, I finally made it by abandoning my browsers and use FileZilla.
