### ISSUE TITLE
Use of Repository. Unable to contact

### ISSUE THREAD

**Issue by ddesotto** [raadon96/MVTec-Anomaly-Detection#75]
Good afternoon, 

I've been trying to contact you to ask for permission to use the code in this repository as inspiration for the resolution of a problem proposed in a math modelling contest by the Universidad Complutense de Madrid. I am a second year Math Student with an interest the use of machine learning to real-world applications and really admire the structure and reasoning in your code

Thank you in advance, and sorry for reaching put in such an unconventional and public way,

**Comment by raadon96** [comment]
Hello,
Yes you may use the code in whatever way you please. It would be nice to get a little citation. Something along the lines of "inspired by ...".
Cheers.

**Comment by ddesotto** [comment]
Thank you! Will definitely credit.
